### ISSUE TITLE
Godot update 3.5.3 on F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [dulvui/ball2box#12]
...while you've bumped it here: https://github.com/dulvui/ball2box/commit/370b5c101aad3e3f3d09b0dd792d7f605e4d7687 and tagged a release, the F-Droid checkupdate CI job picked it up and the current cycle will build it soon.

But the Godot `srclibs:` commit points still to 3.5.2 as that needs to be manually updated.

Will this be an issue? Will the build fail or the game crash once built?

I'm interested to get this updated to 3.5.3 since https://godotengine.org/article/maintenance-release-godot-3-5-3/ and https://blog.isosceles.com/the-webp-0day/

/LE: fyi ref: https://gitlab.com/fdroid/fdroiddata/-/commit/4280f63cf9db62acee63f229affff4af4b0cec8e

**Comment by dulvui** [comment]
Oh you are right, I forgot to update also the `srclibs` to 3.5.3. Thank your very much for the hint!
I upgraded mainly to 3.5.3, to be bale to match Google Play Stores Sdk target 33. So the game won't crash, since there are no new other changes made, except the Godot version used to build the game.

I didn't know that even Godot is affected by the webp 0day, so surely it makes sense to update also on F-Droid urgently.
Is it already possible to use Godot 3.5.3 on F-Droid?

PS: The same counts for Pocket Broomball.

**Comment by licaon-kter** [comment]
Since the game uses your own files, there's less chance to have them touched my malware :) so I'd guess it's not _urgent_.

Buuut, if the app misbehaves because it expects 3.5.3 that's something else. And then we can try to take them down asap and rebuild with 3.5.3

**Comment by dulvui** [comment]
Well you are right, it only uses my files and none is webp
I would not misbehave but I would still update to 3.5.3, if possible. So the changelog about using 3.5.3 is actually correct :)

**Comment by licaon-kter** [comment]
They were built today, we'll try to pull them down and rebuild them next cycle :)

**Comment by dulvui** [comment]
Awesome thank you so much!

**Comment by dulvui** [comment]
I had to update the last recipe build steps for Godot 3.5.3 to create the correct directory and file names.
I did the same for Pocket Broomball and created a Merge request. Now both should build correctly.

MR Ball2Box: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13816
MR Pocket Broomabll: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13815

**Comment by licaon-kter** [comment]
Missed those, thanks  👍
