### ISSUE TITLE
Fullscreen button please

### ISSUE THREAD

**Issue by MadameMalady** [dulvui/ball2box#18]
Hi! I like your game, it works so well on my linux phones ^~^

I was wondering if it'd be possible to add a 'fullscreen' button or setting in options?

when I open the game, I can make the window a little bigger, but not fullscreen, this is what it looks like atm when I open it:
![Screenshot from 2024-09-19 21-38-32](https://github.com/user-attachments/assets/a9a49e03-76f4-493c-b6d2-40575d9d7bd7)

**Comment by dulvui** [comment]
Hello, cool to see the game is played also on Linux phones!
Surely I can add a full-screen button with the next update. I'm currently on vacation, so I don't expect to release a new version for the next to weeks. A new version could arrive at the beginning of October.
I'll keep you updated!

**Comment by MadameMalady** [comment]
Thank you!

**Comment by dulvui** [comment]
@MadameMalady the full screen button is now available in version 4.1.4, but I suppose you got the game from flathub right? Then you might have to wait a few days more, since I need to wait until the Godot 3.6 base image for flatpak is available https://github.com/flathub/org.godotengine.godot.BaseApp/pull/42

**Comment by dulvui** [comment]
Now the update with full screen button, is also available on Flathub.

**Comment by MadameMalady** [comment]
Tested it out, it works great; thank you!

**Comment by dulvui** [comment]
Great! You're welcome
