### ISSUE TITLE
Stars can disappear

### ISSUE THREAD

**Issue by edent** [dulvui/ball2box#2]
Love this game! If I tap to restart just after I've hit a star, it disappears and doesn't respawn. This means I can hit one star, restart, hit the other and claim 3 stars.

![Screenshot_20230223-104519_Ball2Box](https://user-images.githubusercontent.com/837136/220904911-7fbb80f1-dda2-4a50-b913-cdd2c340052a.png)

**Comment by dulvui** [comment]
Thank you very much for opening the issue. Awesome that you love the game!

I'm pretty sure this happens, because I recently added a fade out animation when the ball resets.
So when the star fades in again, the ball is still there while fading out and hits the star again.
Now it should be fixed by adding a "is_hitable" flag that gets set to true when the ball gets shot and to false on reset.
So the star can only get hit, when the ball has been actually shot and not when he is just fading out. 

I will let you know here when the next update with the fixed bug is live in the stores, so you can see if the problem still exists.

**Comment by dulvui** [comment]
The latest update version 2.2.6 fixes now this bug.
Please reopen the issue, if the bug still exists.
