### ISSUE TITLE
Issues after succeeded a level

### ISSUE THREAD

**Issue by Anarky** [dulvui/ball2box#7]
Hello, first of all, thank you for this game!

I found two small issues when a level is finished, please tell me if you prefer two separate issues.

- when a level is finished, if I click on "levels" instead of "next", the level is not considered as done (3 white stars) and the next level can't be selected; returning to the menu fixes it
- when a level is finished, if I close the application and reopen it, it shows the last level played instead of the next one. Not sure if it's really a bug, if I replay an old level and restart the app it will show this old level

PS: I'm using v2.2.6, the latest available on F-Droid.

**Comment by dulvui** [comment]
Hello, thank you for opening the issue!
No problem, It is fine to have everything in one issue.

The first point is surely a bug and I'll try to fix it asap and let you know. It seems that I have to update the level buttons after a level has been completed, since they still show the old state of the stars.

For the second point I think that it is more an usability issue than a bug. Currently the active level gets updated to the new one only if you click on next level. So if you close the app after a level has been completed, without clicking on next level, you will stay on the same level after opening. But I could update the active level to the next one automatically if the level has been completed, so you would see the next level the next time. But i think this logic makes only sense, if you are completing the level for the first time. Otherwise if you try to get 3 stars on a old level you would see the next level when opening the app, instead of the one you are trying to get 3 stars.
If you have any other suggestions let me know!

Side note: There are currently issues with the deployment of updates to F-Droid, so it might take a while until updates are available there.

**Comment by dulvui** [comment]
Now if a level is completed for the first time the next level will appear, if the app gets closed and reopened.
I also removed the levels button for now, because it caused also some other problems like always bringing to the main menu, if back button is clicked. I will refactor the whole menu structure to fix this issue.

F-Droid update is now also working again, so the changes will be visible there too.
When the new version is online, I will close this issue.

**Comment by dulvui** [comment]
Latest version with this issue fixed is now available on all platforms.
